"use client";import{useEffect,useState}from"react";
export default function Home(){const[user,setUser]=useState<any>();const[email,setEmail]=useState("");const[code,setCode]=useState("");const[prompt,setPrompt]=useState("");const[duration,setDuration]=useState(60);const[mode,setMode]=useState("balanced");const[items,setItems]=useState<any[]>([]);const[msg,setMsg]=useState("");
async function refresh(){const m=await fetch("/api/me").then(r=>r.json());setUser(m.user);if(m.user)setItems((await fetch("/api/library").then(r=>r.json())).items||[])}useEffect(()=>{refresh()},[]);
async function send(){setMsg((await fetch("/api/auth/request-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})}).then(r=>r.json())).message||"验证码已发送")}
async function verify(){const j=await fetch("/api/auth/verify-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code})}).then(r=>r.json());setMsg(j.error||"登录成功");refresh()}
async function gen(){const j=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,durationSec:duration,mode})}).then(r=>r.json());setMsg(j.error||"任务已提交");setTimeout(refresh,3000)}
async function subscribe(plan:string){const j=await fetch("/api/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan})}).then(r=>r.json());if(j.url)location.href=j.url;else setMsg(j.error)}
async function portal(){const j=await fetch("/api/billing-portal",{method:"POST"}).then(r=>r.json());if(j.url)location.href=j.url;else setMsg(j.error)}
async function promo(){const code=(document.getElementById("promo") as HTMLInputElement)?.value;const j=await fetch("/api/promo/redeem",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})}).then(r=>r.json());setMsg(j.error||`已增加 ${j.credits} Credits`);refresh()}
async function buy(name:string){const j=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({packageName:name})}).then(r=>r.json());if(j.url)location.href=j.url;else setMsg(j.error)}
return <main><h1>MusicHub AI v0.4</h1><p className="muted">AI音乐 SaaS · Credits · Stripe · R2 · Provider Router · 50%+ 毛利保护</p>{!user?<div className="card"><h3>邮箱登录</h3><input placeholder="邮箱" value={email} onChange={e=>setEmail(e.target.value)}/><div className="grid"><button className="btn" onClick={send}>发送验证码</button><input placeholder="验证码" value={code} onChange={e=>setCode(e.target.value)}/><button className="btn" onClick={verify}>登录</button></div></div>:<div className="card"><b>{user.email}</b> · {user.plan} · Credits <b>{user.credits}</b></div>}<div className="card"><h2>AI音乐生成</h2><textarea rows={5} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="描述风格、情绪、乐器、节奏、用途……"/><div className="grid"><label>时长<select value={duration} onChange={e=>setDuration(+e.target.value)}>{[30,60,120,180,300,600].map(x=><option key={x}>{x}</option>)}</select></label><label>模式<select value={mode} onChange={e=>setMode(e.target.value)}><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="pro">Pro</option></select></label></div><button className="btn" disabled={!user} onClick={gen}>生成音乐</button><p className="muted">{msg}</p></div>{user&&<div className="card"><h2>订阅</h2><div className="grid">{[["basic","Basic","$9.99/月"],["pro","Pro","$24.99/月"],["business","Business","$59.99/月"]].map(p=><div className="card" key={p[0]}><b>{p[1]}</b><div className="price">{p[2]}</div><button className="btn" onClick={()=>subscribe(p[0])}>订阅</button></div>)}</div><button className="btn" onClick={portal}>管理订阅</button></div>}<div className="card"><h2>优惠码</h2><div className="grid"><input id="promo" placeholder="输入优惠码"/><button className="btn" onClick={promo}>兑换</button></div></div><div className="card"><h2>Credits</h2><div className="grid">{[["starter","$9.99","1,000"],["growth","$24.99","3,000"],["scale","$59.99","8,000"]].map(p=><div className="card" key={p[0]}><b>{p[0]}</b><div className="price">{p[1]}</div><p>{p[2]} Credits</p><button className="btn" disabled={!user} onClick={()=>buy(p[0])}>购买</button></div>)}</div></div><div className="card"><h2>我的作品</h2>{items.map(x=><div className="card" key={x.id}><b>{x.status}</b> · {x.durationSec}s<p>{x.prompt}</p>{x.audioUrl&&<audio controls src={x.audioUrl}/>}</div>)}</div></main>}